Milestone - session[:user_id] is now being set correctly across sessions after /login to /meters POST request, now error is 'NameError (undefined local variable or method 'meter_params' for an instance of MetersController):
app/controllers/meters_controller.rb:9:in 'MetersController#create''